id: int64
asn_dn: object
brand: object
country: object
delivered_to_client_date: object
delivery_recorded_date: object
dosage: object
dosage_form: object
first_line_designation: object
freight_cost: object
fulfill_via: object
item_description: object
line_item_insurance: object
line_item_quantity: int64
line_item_value: float64
managed_by: object
manufacturing_site: object
molecule_test_type: object
pack_price: float64
po_sent_to_vendor_date: object
po_so: object
pq: object
pq_first_sent_to_client_date: object
product_group: object
project_code: object
scheduled_delivery_date: object
shipment_mode: object
sub_classification: object
unit_of_measure: int64
unit_price: float64
vendor: object
vendor_inco_term: object
weight: object